name: Deploy on Push to Main

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@master
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Deploy to Server
      run: |
        ssh -o StrictHostKeyChecking=no ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} << 'EOF'
          cd /home/${{ secrets.SSH_USER }}/projects/ai_asr_system

          echo "Stopping existing containers..."
          docker compose down --volumes

          echo "Removing old .env file..."
          rm -f .env

          echo "Creating .env file with secrets..."
          echo 'TELEGRAM_TOKEN=${{ secrets.TELEGRAM_TOKEN }}' > .env
          echo 'DB_USER=${{ secrets.DB_USER }}' >> .env
          echo 'DB_PASSWORD=${{ secrets.DB_PASSWORD }}' >> .env
          echo 'DB_NAME=${{ secrets.DB_NAME }}' >> .env
          echo 'S3_ACCESS_KEY=${{ secrets.S3_ACCESS_KEY }}' >> .env
          echo 'S3_SECRET_KEY=${{ secrets.S3_SECRET_KEY }}' >> .env
          echo 'S3_BUCKET_NAME=${{ secrets.S3_BUCKET_NAME }}' >> .env

          echo "Pulling latest code from GitHub..."
          git pull origin main

          echo "Building and starting Docker containers..."
          docker compose --env-file .env up -d --build
          
          echo "Deployment complete!"
        EOF
